# Devcontainer for the Architecture One-Page site
# Includes Node.js LTS and common tooling
FROM mcr.microsoft.com/devcontainers/javascript-node:20

# Optional: install any global tools you want available in the container
# RUN npm i -g http-server@14.1.1

# The workspace will be mounted at /workspaces/<repo>, no need to COPY files here

EXPOSE 5173
