#!/usr/bin/env node
/**
 * optimize-images.mjs — generate responsive WebP derivatives for every photo
 * referenced by the site, plus a manifest the front-end uses to build srcset.
 *
 *   npm run images
 *
 * Sources in assets/** are left untouched (they are the archive). Derivatives
 * land in assets/derived/** mirroring the source path, and are safe to delete
 * and regenerate at any time.
 *
 * Output per source image:
 *   assets/derived/<path>/<name>-<width>.webp   for each width <= source width
 *   assets/derived/manifest.js                  window.__IMG__ = { "<src>": {w:[...]} }
 */

import sharp from 'sharp';
import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, extname, basename, sep } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIRS = ['assets/projects', 'assets/permit', 'assets/interior-design', 'assets/residential-design'];
const OUT_ROOT = join(root, 'assets', 'derived');
const WIDTHS = [480, 960, 1440, 2000];
const EXT = /\.(jpe?g|png)$/i;

const force = process.argv.includes('--force');
if (force && existsSync(OUT_ROOT)) rmSync(OUT_ROOT, { recursive: true, force: true });

const posix = (p) => p.split(sep).join('/');

function walk(dir, acc = []) {
  if (!existsSync(dir)) return acc;
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, acc);
    else if (EXT.test(name)) acc.push(full);
  }
  return acc;
}

// Only derive images the site actually references. `assets/` stays the full
// archive; deriving all 99 sources would triple the repo for files no page
// ever requests. Add an image to script.js / index.html, re-run, done.
const referenced = new Set(
  ['script.js', 'index.html']
    .filter((f) => existsSync(join(root, f)))
    .flatMap((f) => readFileSync(join(root, f), 'utf8').match(/\.\/assets\/[^'"()\s]+?\.(?:jpe?g|png)/gi) || [])
    .map((p) => p.replace(/^\.\//, ''))
);

const files = SRC_DIRS.flatMap((d) => walk(join(root, d))).filter((f) =>
  referenced.has(posix(relative(root, f)))
);

if (!files.length) {
  console.error('No referenced source images found. Check the paths in script.js.');
  process.exit(1);
}

const manifest = {};
let written = 0;
let skipped = 0;
let bytesIn = 0;
let bytesOut = 0;

for (const file of files) {
  const rel = posix(relative(root, file));               // assets/projects/otaku/x.jpg
  const relDir = dirname(rel);
  const stem = basename(rel, extname(rel));
  const outDir = join(OUT_ROOT, relDir.replace(/^assets\//, ''));
  mkdirSync(outDir, { recursive: true });

  const image = sharp(file, { failOn: 'none' });
  const meta = await image.metadata();
  const srcWidth = meta.width ?? 0;
  bytesIn += statSync(file).size;

  // Keep every standard width the source can fill, and add the source's own
  // width when it sits meaningfully above the largest of them — otherwise a
  // 1280px original would be capped at the 960 rung and lose real detail.
  const widths = WIDTHS.filter((w) => w <= srcWidth);
  const largest = widths.length ? Math.max(...widths) : 0;
  if (srcWidth && srcWidth > largest * 1.15) widths.push(srcWidth);

  const done = [];
  for (const w of widths) {
    const out = join(outDir, `${stem}-${w}.webp`);
    if (existsSync(out) && !force) {
      skipped++;
      done.push(w);
      bytesOut += statSync(out).size;
      continue;
    }
    await sharp(file, { failOn: 'none' })
      .rotate()                                  // honour EXIF orientation
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 })
      .toFile(out);
    written++;
    done.push(w);
    bytesOut += statSync(out).size;
  }

  manifest[`./${rel}`] = {
    b: `./assets/derived/${relDir.replace(/^assets\//, '')}/${stem}`,
    w: done,
    r: srcWidth && meta.height ? +(srcWidth / meta.height).toFixed(4) : null,
  };
}

mkdirSync(OUT_ROOT, { recursive: true });
writeFileSync(
  join(OUT_ROOT, 'manifest.js'),
  '/* Generated by scripts/optimize-images.mjs — do not edit. */\n' +
    'window.__IMG__=' + JSON.stringify(manifest) + ';\n'
);

const mb = (n) => (n / 1048576).toFixed(1) + ' MB';
console.log(`✓ ${written} written, ${skipped} cached, ${files.length} sources`);
console.log(`  originals   ${mb(bytesIn)}`);
console.log(`  derivatives ${mb(bytesOut)}  (all widths combined)`);
console.log(`  manifest    assets/derived/manifest.js`);
